version: "3.2"
services:
  pg:
    build:
      context: ./
      dockerfile: docker/postgres/Dockerfile
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - pgvol:/var/lib/postgresql/data
      - ./docker/postgres/data:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: bureaudevote
      POSTGRES_DB: bureaudevote
      POSTGRES_USER: bureaudevote
      POSTGRES_PORT: 5432
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8901:80
    volumes:
      - pgadminvol:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - pg
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=test

  rabbitmq:
    build:
      context: .
      dockerfile: docker/rabbitmq/Dockerfile
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
      - rabbitvol:/var/lib/rabbitmq
      - ./docker/rabbitmq/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

volumes:
  rabbitvol:
  pgvol:
  pgadminvol:
      