version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.9.7-management
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
      - rabbitvol:/var/lib/rabbitmq
      - ./docker/rabbitmq/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

volumes:
  rabbitvol:
      