version: "3"
services:
  pg:
    image: asinatra/postgres  
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: crypto-executor
      POSTGRES_USER: executor
      POSTGRES_PORT: 5432
      
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8901:80
    volumes:
      - pgvol:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - pg
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=test1234
  
volumes:
  pgvol:
